table PSR_Progress
	lineageTag: 5983a83c-dac4-48a6-a786-b75e92d8fd4f

	column 'PSR_Progress.Miles_Dates_Baseline_Mechanical_Completion_Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bc14e4dc-8f89-4100-8521-cf895bd6d21e
		summarizeBy: none
		sourceColumn: PSR_Progress.Miles_Dates_Baseline_Mechanical_Completion_Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'PSR_Progress.Miles_Dates_Effect_Or_Forecast_Early_Date_Mech_Compl_Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 991993c3-69c2-4832-b22c-e34ce0c82b33
		summarizeBy: none
		sourceColumn: PSR_Progress.Miles_Dates_Effect_Or_Forecast_Early_Date_Mech_Compl_Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'PSR_Progress.Miles_Dates_Effective_or_Forecast_Early_Date_PAC_Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fd65becf-dac9-49a9-a8f3-b23451bbcadf
		summarizeBy: none
		sourceColumn: PSR_Progress.Miles_Dates_Effective_or_Forecast_Early_Date_PAC_Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'PSR_Progress.P_Key'
		dataType: string
		lineageTag: 28502100-70d7-42e6-b7f5-9b7b3daa7125
		summarizeBy: none
		sourceColumn: PSR_Progress.P_Key

		annotation SummarizationSetBy = Automatic

	partition PSR_Progress = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/RISCOP%20BI%20%26%20REPORTING", "PSR Report", [TypedMeasureColumns=true, Implementation="2.0"]),
				    Model1 = Source{[Id="Model"]}[Data],
				    Model2 = Model1{[Id="Model"]}[Data],
				    #"Added Items" = Cube.Transform(Model2,
				        {
				            {Cube.AddAndExpandDimensionColumn, "[PSR_Progress]", {"[PSR_Progress].[CumulatedToDate_perc_Actual_Constr_Subcontr_Direct_Hiring].[CumulatedToDate_perc_Actual_Constr_Subcontr_Direct_Hiring]", "[PSR_Progress].[CumulatedToDate_perc_Actual_for_Commissioning_StartUp].[CumulatedToDate_perc_Actual_for_Commissioning_StartUp]", "[PSR_Progress].[CumulatedToDate_perc_Actual_for_Engineering].[CumulatedToDate_perc_Actual_for_Engineering]", "[PSR_Progress].[CumulatedToDate_perc_Actual_for_Fabrication_All].[CumulatedToDate_perc_Actual_for_Fabrication_All]", "[PSR_Progress].[CumulatedToDate_perc_Actual_for_Hookup].[CumulatedToDate_perc_Actual_for_Hookup]", "[PSR_Progress].[CumulatedToDate_perc_Actual_for_Installation].[CumulatedToDate_perc_Actual_for_Installation]", "[PSR_Progress].[CumulatedToDate_perc_Actual_for_Manufacturing_and_Delivery].[CumulatedToDate_perc_Actual_for_Manufacturing_and_Delivery]", "[PSR_Progress].[CumulatedToDate_perc_Actual_for_Project_Management].[CumulatedToDate_perc_Actual_for_Project_Management]", "[PSR_Progress].[CumulatedToDate_perc_Actual_Overall].[CumulatedToDate_perc_Actual_Overall]", "[PSR_Progress].[CumulatedToDate_perc_Late_Constr_Subcontr_Direct_Hiring].[CumulatedToDate_perc_Late_Constr_Subcontr_Direct_Hiring]", "[PSR_Progress].[CumulatedToDate_perc_Late_for_Commissioning_StartUp].[CumulatedToDate_perc_Late_for_Commissioning_StartUp]", "[PSR_Progress].[CumulatedToDate_perc_Late_for_Engineering].[CumulatedToDate_perc_Late_for_Engineering]", "[PSR_Progress].[CumulatedToDate_perc_Late_for_Fabrication_All].[CumulatedToDate_perc_Late_for_Fabrication_All]", "[PSR_Progress].[CumulatedToDate_perc_Late_for_Hookup].[CumulatedToDate_perc_Late_for_Hookup]", "[PSR_Progress].[CumulatedToDate_perc_Late_for_Installation].[CumulatedToDate_perc_Late_for_Installation]", "[PSR_Progress].[CumulatedToDate_perc_Late_for_Manufacturing_and_Delivery].[CumulatedToDate_perc_Late_for_Manufacturing_and_Delivery]", "[PSR_Progress].[CumulatedToDate_perc_Late_for_Project_Management].[CumulatedToDate_perc_Late_for_Project_Management]", "[PSR_Progress].[CumulatedToDate_perc_Late_Overall].[CumulatedToDate_perc_Late_Overall]", "[PSR_Progress].[CumulatedToDate_perc_Plan_Early_Constr_Subcontr_Direct_Hiring].[CumulatedToDate_perc_Plan_Early_Constr_Subcontr_Direct_Hiring]", "[PSR_Progress].[CumulatedToDate_perc_Plan_Early_for_Commissioning_StartUp].[CumulatedToDate_perc_Plan_Early_for_Commissioning_StartUp]", "[PSR_Progress].[CumulatedToDate_perc_Plan_Early_for_Engineering].[CumulatedToDate_perc_Plan_Early_for_Engineering]", "[PSR_Progress].[CumulatedToDate_perc_Plan_Early_for_Fabrication_All].[CumulatedToDate_perc_Plan_Early_for_Fabrication_All]", "[PSR_Progress].[CumulatedToDate_perc_Plan_Early_for_Hookup].[CumulatedToDate_perc_Plan_Early_for_Hookup]", "[PSR_Progress].[CumulatedToDate_perc_Plan_Early_for_Installation].[CumulatedToDate_perc_Plan_Early_for_Installation]", "[PSR_Progress].[CumulatedToDate_perc_Plan_Early_for_Manufacturing_and_Delivery].[CumulatedToDate_perc_Plan_Early_for_Manufacturing_and_Delivery]", "[PSR_Progress].[CumulatedToDate_perc_Plan_Early_for_Project_Management].[CumulatedToDate_perc_Plan_Early_for_Project_Management]", "[PSR_Progress].[CumulatedToDate_perc_Plan_Early_Overall].[CumulatedToDate_perc_Plan_Early_Overall]", "[PSR_Progress].[End_Date_Baseline].[End_Date_Baseline]", "[PSR_Progress].[End_Date_Forecast].[End_Date_Forecast]", "[PSR_Progress].[Error_Upload].[Error_Upload]", "[PSR_Progress].[ID].[ID]", "[PSR_Progress].[Miles_Dates_Baseline_Effective_Contractual_Starting_Date].[Miles_Dates_Baseline_Effective_Contractual_Starting_Date]", "[PSR_Progress].[Miles_Dates_Baseline_FAC_Date].[Miles_Dates_Baseline_FAC_Date]", "[PSR_Progress].[Miles_Dates_Baseline_Mechanical_Completion_Date].[Miles_Dates_Baseline_Mechanical_Completion_Date]", "[PSR_Progress].[Miles_Dates_Baseline_PAC_Date].[Miles_Dates_Baseline_PAC_Date]", "[PSR_Progress].[Miles_Dates_Effect_Or_Forecast_Early_Date_Mech_Compl_Date].[Miles_Dates_Effect_Or_Forecast_Early_Date_Mech_Compl_Date]", "[PSR_Progress].[Miles_Dates_Effective_or_Forecast_Early_Date_FAC_Date].[Miles_Dates_Effective_or_Forecast_Early_Date_FAC_Date]", "[PSR_Progress].[Miles_Dates_Effective_or_Forecast_Early_Date_PAC_Date].[Miles_Dates_Effective_or_Forecast_Early_Date_PAC_Date]", "[PSR_Progress].[Monthly_perc_Actual_for_Commissioning_StartUp].[Monthly_perc_Actual_for_Commissioning_StartUp]", "[PSR_Progress].[Monthly_perc_Actual_for_Constr_Subcontr_Direct_Hiring].[Monthly_perc_Actual_for_Constr_Subcontr_Direct_Hiring]", "[PSR_Progress].[Monthly_perc_Actual_for_Engineering].[Monthly_perc_Actual_for_Engineering]", "[PSR_Progress].[Monthly_perc_Actual_for_Fabrication_All].[Monthly_perc_Actual_for_Fabrication_All]", "[PSR_Progress].[Monthly_perc_Actual_for_Hookup].[Monthly_perc_Actual_for_Hookup]", "[PSR_Progress].[Monthly_perc_Actual_for_Installation].[Monthly_perc_Actual_for_Installation]", "[PSR_Progress].[Monthly_perc_Actual_for_Manufacturing_and_Delivery].[Monthly_perc_Actual_for_Manufacturing_and_Delivery]", "[PSR_Progress].[Monthly_perc_Actual_for_Project_Management].[Monthly_perc_Actual_for_Project_Management]", "[PSR_Progress].[Monthly_perc_Actual_Overall].[Monthly_perc_Actual_Overall]", "[PSR_Progress].[Monthly_perc_Plan_Early_for_Commissioning_StartUp].[Monthly_perc_Plan_Early_for_Commissioning_StartUp]", "[PSR_Progress].[Monthly_perc_Plan_Early_for_Constr_Subcontr_Direct_Hiring].[Monthly_perc_Plan_Early_for_Constr_Subcontr_Direct_Hiring]", "[PSR_Progress].[Monthly_perc_Plan_Early_for_Engineering].[Monthly_perc_Plan_Early_for_Engineering]", "[PSR_Progress].[Monthly_perc_Plan_Early_for_Fabrication_All].[Monthly_perc_Plan_Early_for_Fabrication_All]", "[PSR_Progress].[Monthly_perc_Plan_Early_for_Hookup].[Monthly_perc_Plan_Early_for_Hookup]", "[PSR_Progress].[Monthly_perc_Plan_Early_for_Installation].[Monthly_perc_Plan_Early_for_Installation]", "[PSR_Progress].[Monthly_perc_Plan_Early_for_Manufacturing_and_Delivery].[Monthly_perc_Plan_Early_for_Manufacturing_and_Delivery]", "[PSR_Progress].[Monthly_perc_Plan_Early_for_Project_Management].[Monthly_perc_Plan_Early_for_Project_Management]", "[PSR_Progress].[Monthly_perc_Plan_Early_Overall].[Monthly_perc_Plan_Early_Overall]", "[PSR_Progress].[P_Key].[P_Key]", "[PSR_Progress].[Relative_Weight_perc_for_Commissioning_StartUp].[Relative_Weight_perc_for_Commissioning_StartUp]", "[PSR_Progress].[Relative_Weight_perc_for_Constr_Subcontr_Direct_Hiring].[Relative_Weight_perc_for_Constr_Subcontr_Direct_Hiring]", "[PSR_Progress].[Relative_Weight_perc_for_Engineering].[Relative_Weight_perc_for_Engineering]", "[PSR_Progress].[Relative_Weight_perc_for_Fabrication_All].[Relative_Weight_perc_for_Fabrication_All]", "[PSR_Progress].[Relative_Weight_perc_for_Hookup].[Relative_Weight_perc_for_Hookup]", "[PSR_Progress].[Relative_Weight_perc_for_Installation].[Relative_Weight_perc_for_Installation]", "[PSR_Progress].[Relative_Weight_perc_for_Manufacturing_and_Delivery].[Relative_Weight_perc_for_Manufacturing_and_Delivery]", "[PSR_Progress].[Relative_Weight_perc_for_Project_Management].[Relative_Weight_perc_for_Project_Management]"}, {"PSR_Progress.CumulatedToDate_perc_Actual_Constr_Subcontr_Direct_Hiring", "PSR_Progress.CumulatedToDate_perc_Actual_for_Commissioning_StartUp", "PSR_Progress.CumulatedToDate_perc_Actual_for_Engineering", "PSR_Progress.CumulatedToDate_perc_Actual_for_Fabrication_All", "PSR_Progress.CumulatedToDate_perc_Actual_for_Hookup", "PSR_Progress.CumulatedToDate_perc_Actual_for_Installation", "PSR_Progress.CumulatedToDate_perc_Actual_for_Manufacturing_and_Delivery", "PSR_Progress.CumulatedToDate_perc_Actual_for_Project_Management", "PSR_Progress.CumulatedToDate_perc_Actual_Overall", "PSR_Progress.CumulatedToDate_perc_Late_Constr_Subcontr_Direct_Hiring", "PSR_Progress.CumulatedToDate_perc_Late_for_Commissioning_StartUp", "PSR_Progress.CumulatedToDate_perc_Late_for_Engineering", "PSR_Progress.CumulatedToDate_perc_Late_for_Fabrication_All", "PSR_Progress.CumulatedToDate_perc_Late_for_Hookup", "PSR_Progress.CumulatedToDate_perc_Late_for_Installation", "PSR_Progress.CumulatedToDate_perc_Late_for_Manufacturing_and_Delivery", "PSR_Progress.CumulatedToDate_perc_Late_for_Project_Management", "PSR_Progress.CumulatedToDate_perc_Late_Overall", "PSR_Progress.CumulatedToDate_perc_Plan_Early_Constr_Subcontr_Direct_Hiring", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Commissioning_StartUp", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Engineering", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Fabrication_All", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Hookup", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Installation", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Manufacturing_and_Delivery", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Project_Management", "PSR_Progress.CumulatedToDate_perc_Plan_Early_Overall", "PSR_Progress.End_Date_Baseline", "PSR_Progress.End_Date_Forecast", "PSR_Progress.Error_Upload", "PSR_Progress.ID", "PSR_Progress.Miles_Dates_Baseline_Effective_Contractual_Starting_Date", "PSR_Progress.Miles_Dates_Baseline_FAC_Date", "PSR_Progress.Miles_Dates_Baseline_Mechanical_Completion_Date", "PSR_Progress.Miles_Dates_Baseline_PAC_Date", "PSR_Progress.Miles_Dates_Effect_Or_Forecast_Early_Date_Mech_Compl_Date", "PSR_Progress.Miles_Dates_Effective_or_Forecast_Early_Date_FAC_Date", "PSR_Progress.Miles_Dates_Effective_or_Forecast_Early_Date_PAC_Date", "PSR_Progress.Monthly_perc_Actual_for_Commissioning_StartUp", "PSR_Progress.Monthly_perc_Actual_for_Constr_Subcontr_Direct_Hiring", "PSR_Progress.Monthly_perc_Actual_for_Engineering", "PSR_Progress.Monthly_perc_Actual_for_Fabrication_All", "PSR_Progress.Monthly_perc_Actual_for_Hookup", "PSR_Progress.Monthly_perc_Actual_for_Installation", "PSR_Progress.Monthly_perc_Actual_for_Manufacturing_and_Delivery", "PSR_Progress.Monthly_perc_Actual_for_Project_Management", "PSR_Progress.Monthly_perc_Actual_Overall", "PSR_Progress.Monthly_perc_Plan_Early_for_Commissioning_StartUp", "PSR_Progress.Monthly_perc_Plan_Early_for_Constr_Subcontr_Direct_Hiring", "PSR_Progress.Monthly_perc_Plan_Early_for_Engineering", "PSR_Progress.Monthly_perc_Plan_Early_for_Fabrication_All", "PSR_Progress.Monthly_perc_Plan_Early_for_Hookup", "PSR_Progress.Monthly_perc_Plan_Early_for_Installation", "PSR_Progress.Monthly_perc_Plan_Early_for_Manufacturing_and_Delivery", "PSR_Progress.Monthly_perc_Plan_Early_for_Project_Management", "PSR_Progress.Monthly_perc_Plan_Early_Overall", "PSR_Progress.P_Key", "PSR_Progress.Relative_Weight_perc_for_Commissioning_StartUp", "PSR_Progress.Relative_Weight_perc_for_Constr_Subcontr_Direct_Hiring", "PSR_Progress.Relative_Weight_perc_for_Engineering", "PSR_Progress.Relative_Weight_perc_for_Fabrication_All", "PSR_Progress.Relative_Weight_perc_for_Hookup", "PSR_Progress.Relative_Weight_perc_for_Installation", "PSR_Progress.Relative_Weight_perc_for_Manufacturing_and_Delivery", "PSR_Progress.Relative_Weight_perc_for_Project_Management"}},
				            {Cube.AddMeasureColumn, "Mech CompletionDate Diff", "[Measures].[Mech CompletionDate Diff]"}
				        }),
				
				    // Filtro per rimuovere dati prima del 2022 (non essendoci una colonna "anno", il filtro è applicato cercando delle stringhe nella chiave)
				    #"Filtered Rows_year" = Table.SelectRows(#"Added Items", each not Text.Contains([PSR_Progress.P_Key], "_2010_") and not Text.Contains([PSR_Progress.P_Key], "_2011_") and not Text.Contains([PSR_Progress.P_Key], "_2012_") and not Text.Contains([PSR_Progress.P_Key], "_2013_") and not Text.Contains([PSR_Progress.P_Key], "_2014_") and not Text.Contains([PSR_Progress.P_Key], "_2015_") and not Text.Contains([PSR_Progress.P_Key], "_2016_") and not Text.Contains([PSR_Progress.P_Key], "_2017_") and not Text.Contains([PSR_Progress.P_Key], "_2018_") and not Text.Contains([PSR_Progress.P_Key], "_2019_") and not Text.Contains([PSR_Progress.P_Key], "_2020_") and not Text.Contains([PSR_Progress.P_Key], "_2021_")),
				
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows_year",{"Mech CompletionDate Diff", "PSR_Progress.CumulatedToDate_perc_Actual_Constr_Subcontr_Direct_Hiring", "PSR_Progress.CumulatedToDate_perc_Actual_for_Commissioning_StartUp", "PSR_Progress.CumulatedToDate_perc_Actual_for_Engineering", "PSR_Progress.CumulatedToDate_perc_Actual_for_Fabrication_All", "PSR_Progress.CumulatedToDate_perc_Actual_for_Hookup", "PSR_Progress.CumulatedToDate_perc_Actual_for_Installation", "PSR_Progress.CumulatedToDate_perc_Actual_for_Manufacturing_and_Delivery", "PSR_Progress.CumulatedToDate_perc_Actual_for_Project_Management", "PSR_Progress.CumulatedToDate_perc_Actual_Overall", "PSR_Progress.CumulatedToDate_perc_Late_Constr_Subcontr_Direct_Hiring", "PSR_Progress.CumulatedToDate_perc_Late_for_Commissioning_StartUp", "PSR_Progress.CumulatedToDate_perc_Late_for_Engineering", "PSR_Progress.CumulatedToDate_perc_Late_for_Fabrication_All", "PSR_Progress.CumulatedToDate_perc_Late_for_Hookup", "PSR_Progress.CumulatedToDate_perc_Late_for_Installation", "PSR_Progress.CumulatedToDate_perc_Late_for_Manufacturing_and_Delivery", "PSR_Progress.CumulatedToDate_perc_Late_for_Project_Management", "PSR_Progress.CumulatedToDate_perc_Late_Overall", "PSR_Progress.CumulatedToDate_perc_Plan_Early_Constr_Subcontr_Direct_Hiring", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Commissioning_StartUp", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Engineering", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Fabrication_All", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Hookup", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Installation", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Manufacturing_and_Delivery", "PSR_Progress.CumulatedToDate_perc_Plan_Early_for_Project_Management", "PSR_Progress.CumulatedToDate_perc_Plan_Early_Overall", "PSR_Progress.End_Date_Baseline", "PSR_Progress.End_Date_Forecast", "PSR_Progress.Error_Upload", "PSR_Progress.ID", "PSR_Progress.Miles_Dates_Baseline_Effective_Contractual_Starting_Date", "PSR_Progress.Miles_Dates_Baseline_FAC_Date", "PSR_Progress.Miles_Dates_Effective_or_Forecast_Early_Date_FAC_Date", "PSR_Progress.Monthly_perc_Actual_for_Commissioning_StartUp", "PSR_Progress.Monthly_perc_Actual_for_Constr_Subcontr_Direct_Hiring", "PSR_Progress.Monthly_perc_Actual_for_Engineering", "PSR_Progress.Monthly_perc_Actual_for_Fabrication_All", "PSR_Progress.Monthly_perc_Actual_for_Hookup", "PSR_Progress.Monthly_perc_Actual_for_Installation", "PSR_Progress.Monthly_perc_Actual_for_Manufacturing_and_Delivery", "PSR_Progress.Monthly_perc_Actual_for_Project_Management", "PSR_Progress.Monthly_perc_Actual_Overall", "PSR_Progress.Monthly_perc_Plan_Early_for_Commissioning_StartUp", "PSR_Progress.Monthly_perc_Plan_Early_for_Constr_Subcontr_Direct_Hiring", "PSR_Progress.Monthly_perc_Plan_Early_for_Engineering", "PSR_Progress.Monthly_perc_Plan_Early_for_Fabrication_All", "PSR_Progress.Monthly_perc_Plan_Early_for_Hookup", "PSR_Progress.Monthly_perc_Plan_Early_for_Installation", "PSR_Progress.Monthly_perc_Plan_Early_for_Manufacturing_and_Delivery", "PSR_Progress.Monthly_perc_Plan_Early_for_Project_Management", "PSR_Progress.Monthly_perc_Plan_Early_Overall", "PSR_Progress.Relative_Weight_perc_for_Commissioning_StartUp", "PSR_Progress.Relative_Weight_perc_for_Constr_Subcontr_Direct_Hiring", "PSR_Progress.Relative_Weight_perc_for_Engineering", "PSR_Progress.Relative_Weight_perc_for_Fabrication_All", "PSR_Progress.Relative_Weight_perc_for_Hookup", "PSR_Progress.Relative_Weight_perc_for_Installation", "PSR_Progress.Relative_Weight_perc_for_Manufacturing_and_Delivery", "PSR_Progress.Relative_Weight_perc_for_Project_Management", "PSR_Progress.Miles_Dates_Baseline_PAC_Date"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

