table PSR_Risks_Opportunity
	lineageTag: 5cdc68dd-9bf1-4250-b667-87d385da2e48

	column 'PSR_Risks_Opportunities.Gross_Margin_Conf_Level_Current_Forecast_Montecarlo_Anal'
		dataType: string
		lineageTag: e933a8f5-faff-471f-8a11-4945ec86c109
		summarizeBy: none
		sourceColumn: PSR_Risks_Opportunities.Gross_Margin_Conf_Level_Current_Forecast_Montecarlo_Anal

		annotation SummarizationSetBy = Automatic

	column 'PSR_Risks_Opportunities.P_Key'
		dataType: string
		lineageTag: e96b2429-7b3f-4609-8ec4-987edce56f3f
		summarizeBy: none
		sourceColumn: PSR_Risks_Opportunities.P_Key

		annotation SummarizationSetBy = Automatic

	column 'PSR_Risks_Opportunities.VAR_75'
		dataType: int64
		formatString: #,0
		lineageTag: 101e60dd-45bd-4db0-a1a3-d39085f1d4ef
		summarizeBy: none
		sourceColumn: PSR_Risks_Opportunities.VAR_75

		annotation SummarizationSetBy = Automatic

	column 'PRR (Project Risk Rate)'
		dataType: int64
		formatString: 0
		lineageTag: 7b8a4ac0-d960-4bbe-8db7-c3f73a7046e1
		summarizeBy: none
		sourceColumn: PRR (Project Risk Rate)

		annotation SummarizationSetBy = Automatic

	column _Gross_Margin_Confidence_Level = ```
			
			
			SUBSTITUTE(
			    [PSR_Risks_Opportunities.Gross_Margin_Conf_Level_Current_Forecast_Montecarlo_Anal],
			    "%", 
			    ""
			) / 100
			```
		dataType: double
		formatString: 0.00
		lineageTag: cc9e467c-6b90-49da-a732-71128340fd8c
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition PSR_Risks_Opportunity = m
		mode: import
		source = ```
				let
				    Source = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/RISCOP%20BI%20%26%20REPORTING", "PSR Report", [TypedMeasureColumns=true, Implementation="2.0"]),
				    Model1 = Source{[Id="Model"]}[Data],
				    Model2 = Model1{[Id="Model"]}[Data],
				    #"Added Items" = Cube.Transform(Model2,
				        {
				            {Cube.AddAndExpandDimensionColumn, "[PSR_Risks_Opportunities]", {"[PSR_Risks_Opportunities].[CF_Management_Contingencies].[CF_Management_Contingencies]", "[PSR_Risks_Opportunities].[CF_Project_Contingencies].[CF_Project_Contingencies]", "[PSR_Risks_Opportunities].[Error_Upload].[Error_Upload]", "[PSR_Risks_Opportunities].[GMCL].[GMCL]", "[PSR_Risks_Opportunities].[GMCL Score].[GMCL Score]", "[PSR_Risks_Opportunities].[Gross_Margin_Conf_Level_Current_Forecast_Montecarlo_Analysis].[Gross_Margin_Conf_Level_Current_Forecast_Montecarlo_Analysis]", "[PSR_Risks_Opportunities].[ID].[ID]", "[PSR_Risks_Opportunities].[Net_Risk_OCB].[Net_Risk_OCB]", "[PSR_Risks_Opportunities].[Net_Risk_RCB].[Net_Risk_RCB]", "[PSR_Risks_Opportunities].[Opp_Expected_Current_Forecast_for_Constr_Inst].[Opp_Expected_Current_Forecast_for_Constr_Inst]", "[PSR_Risks_Opportunities].[Opp_Expected_Current_Forecast_for_Country].[Opp_Expected_Current_Forecast_for_Country]", "[PSR_Risks_Opportunities].[Opp_Expected_Current_Forecast_for_Eng].[Opp_Expected_Current_Forecast_for_Eng]", "[PSR_Risks_Opportunities].[Opp_Expected_Current_Forecast_for_Ext_of_Time].[Opp_Expected_Current_Forecast_for_Ext_of_Time]", "[PSR_Risks_Opportunities].[Opp_Expected_Current_Forecast_for_Hand_over_with_Proposal].[Opp_Expected_Current_Forecast_for_Hand_over_with_Proposal]", "[PSR_Risks_Opportunities].[Opp_Expected_Current_Forecast_for_Prj_Mng].[Opp_Expected_Current_Forecast_for_Prj_Mng]", "[PSR_Risks_Opportunities].[Opp_Expected_Current_Forecast_for_Proc].[Opp_Expected_Current_Forecast_for_Proc]", "[PSR_Risks_Opportunities].[Opp_Expected_Current_Forecast_Total].[Opp_Expected_Current_Forecast_Total]", "[PSR_Risks_Opportunities].[Opp_Occur_As_Prj_Conting_for_Constr_Inst].[Opp_Occur_As_Prj_Conting_for_Constr_Inst]", "[PSR_Risks_Opportunities].[Opp_Occur_As_Prj_Conting_for_Country].[Opp_Occur_As_Prj_Conting_for_Country]", "[PSR_Risks_Opportunities].[Opp_Occur_As_Prj_Conting_for_Eng].[Opp_Occur_As_Prj_Conting_for_Eng]", "[PSR_Risks_Opportunities].[Opp_Occur_As_Prj_Conting_for_Ext_of_Time].[Opp_Occur_As_Prj_Conting_for_Ext_of_Time]", "[PSR_Risks_Opportunities].[Opp_Occur_As_Prj_Conting_for_Hand_Over_with_Proposal].[Opp_Occur_As_Prj_Conting_for_Hand_Over_with_Proposal]", "[PSR_Risks_Opportunities].[Opp_Occur_As_Prj_Conting_for_Prj_Mng].[Opp_Occur_As_Prj_Conting_for_Prj_Mng]", "[PSR_Risks_Opportunities].[Opp_Occur_As_Prj_Conting_for_Proc].[Opp_Occur_As_Prj_Conting_for_Proc]", "[PSR_Risks_Opportunities].[Opp_Occur_As_Prj_Conting_Total].[Opp_Occur_As_Prj_Conting_Total]", "[PSR_Risks_Opportunities].[Opp_Occur_Effect_Margin_Impact_for_Constr_Inst].[Opp_Occur_Effect_Margin_Impact_for_Constr_Inst]", "[PSR_Risks_Opportunities].[Opp_Occur_Effect_Margin_Impact_for_Country].[Opp_Occur_Effect_Margin_Impact_for_Country]", "[PSR_Risks_Opportunities].[Opp_Occur_Effect_Margin_Impact_for_Eng].[Opp_Occur_Effect_Margin_Impact_for_Eng]", "[PSR_Risks_Opportunities].[Opp_Occur_Effect_Margin_Impact_for_Ext_of_Time].[Opp_Occur_Effect_Margin_Impact_for_Ext_of_Time]", "[PSR_Risks_Opportunities].[Opp_Occur_Effect_Margin_Impact_for_Hand_over_with_Proposal].[Opp_Occur_Effect_Margin_Impact_for_Hand_over_with_Proposal]", "[PSR_Risks_Opportunities].[Opp_Occur_Effect_Margin_Impact_for_Prj_Mng].[Opp_Occur_Effect_Margin_Impact_for_Prj_Mng]", "[PSR_Risks_Opportunities].[Opp_Occur_Effect_Margin_Impact_for_Proc].[Opp_Occur_Effect_Margin_Impact_for_Proc]", "[PSR_Risks_Opportunities].[Opp_Occur_Effect_Margin_Impact_Total].[Opp_Occur_Effect_Margin_Impact_Total]", "[PSR_Risks_Opportunities].[P_Key].[P_Key]", "[PSR_Risks_Opportunities].[Range_Of_Gross_Margin_Forecast_Downside_worst_case].[Range_Of_Gross_Margin_Forecast_Downside_worst_case]", "[PSR_Risks_Opportunities].[Range_Of_Gross_Margin_Forecast_Upside_best_case].[Range_Of_Gross_Margin_Forecast_Upside_best_case]", "[PSR_Risks_Opportunities].[Risk_Coverage].[Risk_Coverage]", "[PSR_Risks_Opportunities].[Risk_Exposure].[Risk_Exposure]", "[PSR_Risks_Opportunities].[Risk_Ratio].[Risk_Ratio]", "[PSR_Risks_Opportunities].[Risk_Register_Reference_Portal_ID].[Risk_Register_Reference_Portal_ID]", "[PSR_Risks_Opportunities].[Risks_Expected_Current_Forecast_Eng].[Risks_Expected_Current_Forecast_Eng]", "[PSR_Risks_Opportunities].[Risks_Expected_Current_Forecast_for_Constr_Inst].[Risks_Expected_Current_Forecast_for_Constr_Inst]", "[PSR_Risks_Opportunities].[Risks_Expected_Current_Forecast_for_Country].[Risks_Expected_Current_Forecast_for_Country]", "[PSR_Risks_Opportunities].[Risks_Expected_Current_Forecast_for_Hand_over_with_Proposal].[Risks_Expected_Current_Forecast_for_Hand_over_with_Proposal]", "[PSR_Risks_Opportunities].[Risks_Expected_Current_Forecast_for_Liquidated_Damages].[Risks_Expected_Current_Forecast_for_Liquidated_Damages]", "[PSR_Risks_Opportunities].[Risks_Expected_Current_Forecast_for_Prj_Mng].[Risks_Expected_Current_Forecast_for_Prj_Mng]", "[PSR_Risks_Opportunities].[Risks_Expected_Current_Forecast_for_Proc].[Risks_Expected_Current_Forecast_for_Proc]", "[PSR_Risks_Opportunities].[Risks_Expected_Current_Forecast_Running_Costs_for_Delay].[Risks_Expected_Current_Forecast_Running_Costs_for_Delay]", "[PSR_Risks_Opportunities].[Risks_Expected_Current_Forecast_Total].[Risks_Expected_Current_Forecast_Total]", "[PSR_Risks_Opportunities].[Risks_Mng_Conting_Current_Forecast_for_Constr_Inst].[Risks_Mng_Conting_Current_Forecast_for_Constr_Inst]", "[PSR_Risks_Opportunities].[Risks_Mng_Conting_Current_Forecast_for_Country].[Risks_Mng_Conting_Current_Forecast_for_Country]", "[PSR_Risks_Opportunities].[Risks_Mng_Conting_Current_Forecast_for_Eng].[Risks_Mng_Conting_Current_Forecast_for_Eng]", "[PSR_Risks_Opportunities].[Risks_Mng_Conting_Current_Forecast_for_Hand_Over_with_Proposal].[Risks_Mng_Conting_Current_Forecast_for_Hand_Over_with_Proposal]", "[PSR_Risks_Opportunities].[Risks_Mng_Conting_Current_Forecast_for_Liquidated_Damages].[Risks_Mng_Conting_Current_Forecast_for_Liquidated_Damages]", "[PSR_Risks_Opportunities].[Risks_Mng_Conting_Current_Forecast_for_Prj_Mng].[Risks_Mng_Conting_Current_Forecast_for_Prj_Mng]", "[PSR_Risks_Opportunities].[Risks_Mng_Conting_Current_Forecast_for_Proc].[Risks_Mng_Conting_Current_Forecast_for_Proc]", "[PSR_Risks_Opportunities].[Risks_Mng_Conting_Current_Forecast_for_Running_Costs_for_Delay].[Risks_Mng_Conting_Current_Forecast_for_Running_Costs_for_Delay]", "[PSR_Risks_Opportunities].[Risks_Occur_Effect_Margin_Impact_Eng].[Risks_Occur_Effect_Margin_Impact_Eng]", "[PSR_Risks_Opportunities].[Risks_Occur_Effect_Margin_Impact_for_Constr_Inst].[Risks_Occur_Effect_Margin_Impact_for_Constr_Inst]", "[PSR_Risks_Opportunities].[Risks_Occur_Effect_Margin_Impact_for_Country].[Risks_Occur_Effect_Margin_Impact_for_Country]", "[PSR_Risks_Opportunities].[Risks_Occur_Effect_Margin_Impact_for_Hand_over_with_Proposal].[Risks_Occur_Effect_Margin_Impact_for_Hand_over_with_Proposal]", "[PSR_Risks_Opportunities].[Risks_Occur_Effect_Margin_Impact_for_Liquidated_Damages].[Risks_Occur_Effect_Margin_Impact_for_Liquidated_Damages]", "[PSR_Risks_Opportunities].[Risks_Occur_Effect_Margin_Impact_for_Prj_Mng].[Risks_Occur_Effect_Margin_Impact_for_Prj_Mng]", "[PSR_Risks_Opportunities].[Risks_Occur_Effect_Margin_Impact_for_Proc].[Risks_Occur_Effect_Margin_Impact_for_Proc]", "[PSR_Risks_Opportunities].[Risks_Occur_Effect_Margin_Impact_Running_Costs_for_Delay].[Risks_Occur_Effect_Margin_Impact_Running_Costs_for_Delay]", "[PSR_Risks_Opportunities].[Risks_Occur_Effect_Margin_Impact_Total].[Risks_Occur_Effect_Margin_Impact_Total]", "[PSR_Risks_Opportunities].[Risks_Occur_Utilized_Conting_for_Constr_Inst].[Risks_Occur_Utilized_Conting_for_Constr_Inst]", "[PSR_Risks_Opportunities].[Risks_Occur_Utilized_Conting_for_Country].[Risks_Occur_Utilized_Conting_for_Country]", "[PSR_Risks_Opportunities].[Risks_Occur_Utilized_Conting_for_Eng].[Risks_Occur_Utilized_Conting_for_Eng]", "[PSR_Risks_Opportunities].[Risks_Occur_Utilized_Conting_for_Hand_Over_with_Proposal].[Risks_Occur_Utilized_Conting_for_Hand_Over_with_Proposal]", "[PSR_Risks_Opportunities].[Risks_Occur_Utilized_Conting_for_Liquidated_Damages].[Risks_Occur_Utilized_Conting_for_Liquidated_Damages]", "[PSR_Risks_Opportunities].[Risks_Occur_Utilized_Conting_for_Prj_Mng].[Risks_Occur_Utilized_Conting_for_Prj_Mng]", "[PSR_Risks_Opportunities].[Risks_Occur_Utilized_Conting_for_Proc].[Risks_Occur_Utilized_Conting_for_Proc]", "[PSR_Risks_Opportunities].[Risks_Occur_Utilized_Conting_for_Running_Costs_for_Delay].[Risks_Occur_Utilized_Conting_for_Running_Costs_for_Delay]", "[PSR_Risks_Opportunities].[Risks_Occur_Utilized_Conting_Total].[Risks_Occur_Utilized_Conting_Total]", "[PSR_Risks_Opportunities].[Risks_Prj_Conting_Current_Forecast_for_Constr_Inst].[Risks_Prj_Conting_Current_Forecast_for_Constr_Inst]", "[PSR_Risks_Opportunities].[Risks_Prj_Conting_Current_Forecast_for_Country].[Risks_Prj_Conting_Current_Forecast_for_Country]", "[PSR_Risks_Opportunities].[Risks_Prj_Conting_Current_Forecast_for_Eng].[Risks_Prj_Conting_Current_Forecast_for_Eng]", "[PSR_Risks_Opportunities].[Risks_Prj_Conting_Current_Forecast_for_Hand_Over_with_Proposal].[Risks_Prj_Conting_Current_Forecast_for_Hand_Over_with_Proposal]", "[PSR_Risks_Opportunities].[Risks_Prj_Conting_Current_Forecast_for_Liquidated_Damages].[Risks_Prj_Conting_Current_Forecast_for_Liquidated_Damages]", "[PSR_Risks_Opportunities].[Risks_Prj_Conting_Current_Forecast_for_Prj_Mng].[Risks_Prj_Conting_Current_Forecast_for_Prj_Mng]", "[PSR_Risks_Opportunities].[Risks_Prj_Conting_Current_Forecast_for_Proc].[Risks_Prj_Conting_Current_Forecast_for_Proc]", "[PSR_Risks_Opportunities].[Risks_Prj_Conting_Current_Forecast_for_Running_Costs_for_Delay].[Risks_Prj_Conting_Current_Forecast_for_Running_Costs_for_Delay]", "[PSR_Risks_Opportunities].[Risks_Residual_Expected_Current_Forecast_Total].[Risks_Residual_Expected_Current_Forecast_Total]", "[PSR_Risks_Opportunities].[Total_Opportunities_OCB].[Total_Opportunities_OCB]", "[PSR_Risks_Opportunities].[Total_Opportunities_RCB].[Total_Opportunities_RCB]", "[PSR_Risks_Opportunities].[Total_Revenues_Included_In_Forecast].[Total_Revenues_Included_In_Forecast]", "[PSR_Risks_Opportunities].[Total_Risk_OCB].[Total_Risk_OCB]", "[PSR_Risks_Opportunities].[Total_Risk_RCB].[Total_Risk_RCB]", "[PSR_Risks_Opportunities].[VAR 75 Score].[VAR 75 Score]", "[PSR_Risks_Opportunities].[VAR_50].[VAR_50]", "[PSR_Risks_Opportunities].[VAR_75].[VAR_75]"}, {"PSR_Risks_Opportunities.CF_Management_Contingencies", "PSR_Risks_Opportunities.CF_Project_Contingencies", "PSR_Risks_Opportunities.Error_Upload", "PSR_Risks_Opportunities.GMCL", "PSR_Risks_Opportunities.GMCL Score", "PSR_Risks_Opportunities.Gross_Margin_Conf_Level_Current_Forecast_Montecarlo_Anal", "PSR_Risks_Opportunities.ID", "PSR_Risks_Opportunities.Net_Risk_OCB", "PSR_Risks_Opportunities.Net_Risk_RCB", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Constr_Inst", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Country", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Eng", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Ext_of_Time", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Hand_over_with_Proposa", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Prj_Mng", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Proc", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_Total", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Constr_Inst", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Country", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Eng", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Ext_of_Time", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Hand_Over_with_Proposal", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Prj_Mng", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Proc", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_Total", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Constr_Inst", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Country", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Eng", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Ext_of_Time", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Hand_over_with_Propos", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Prj_Mng", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Proc", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_Total", "PSR_Risks_Opportunities.P_Key", "PSR_Risks_Opportunities.Range_Of_Gross_Margin_Forecast_Downside_worst_case", "PSR_Risks_Opportunities.Range_Of_Gross_Margin_Forecast_Upside_best_case", "PSR_Risks_Opportunities.Risk_Coverage", "PSR_Risks_Opportunities.Risk_Exposure", "PSR_Risks_Opportunities.Risk_Ratio", "PSR_Risks_Opportunities.Risk_Register_Reference_Portal_ID", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_Eng", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Country", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Hand_over_with_Propo", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Liquidated_Damages", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Proc", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_Running_Costs_for_Delay", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_Total", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Country", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Eng", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Hand_Over_with_Pr", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Liquidated_Damage", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Proc", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Running_Costs_for", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_Eng", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Country", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Hand_over_with_Prop", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Liquidated_Damages", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Proc", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_Running_Costs_for_Delay", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_Total", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Country", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Eng", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Hand_Over_with_Proposal", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Liquidated_Damages", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Proc", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Running_Costs_for_Delay", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_Total", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Country", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Eng", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Hand_Over_with_Pr", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Liquidated_Damage", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Proc", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Running_Costs_for", "PSR_Risks_Opportunities.Risks_Residual_Expected_Current_Forecast_Total", "PSR_Risks_Opportunities.Total_Opportunities_OCB", "PSR_Risks_Opportunities.Total_Opportunities_RCB", "PSR_Risks_Opportunities.Total_Revenues_Included_In_Forecast", "PSR_Risks_Opportunities.Total_Risk_OCB", "PSR_Risks_Opportunities.Total_Risk_RCB", "PSR_Risks_Opportunities.VAR 75 Score", "PSR_Risks_Opportunities.VAR_50", "PSR_Risks_Opportunities.VAR_75"}},
				            {Cube.AddMeasureColumn, "PRR (Project Risk Rate)", "[Measures].[PRR (Project Risk Rate)]"},
				            {Cube.AddMeasureColumn, "PRR Cluster", "[Measures].[PRR Cluster]"},
				            {Cube.AddMeasureColumn, "PRR Color", "[Measures].[PRR Color]"},
				            {Cube.AddMeasureColumn, "Risk Delay", "[Measures].[Risk Delay]"}
				        }),
				    
				    // Filtro per rimuovere dati prima del 2022 (non essendoci una colonna "anno", il filtro è applicato cercando delle stringhe nella chiave)
				    #"Filtered Rows_year" = Table.SelectRows(#"Added Items", each not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2010_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2011_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2012_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2013_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2014_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2015_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2016_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2017_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2018_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2019_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2020_") and not Text.Contains([PSR_Risks_Opportunities.P_Key], "_2021_")),
				
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows_year",{"PRR Cluster", "PRR Color", "Risk Delay", "PSR_Risks_Opportunities.CF_Management_Contingencies", "PSR_Risks_Opportunities.CF_Project_Contingencies", "PSR_Risks_Opportunities.Error_Upload", "PSR_Risks_Opportunities.GMCL", "PSR_Risks_Opportunities.GMCL Score", "PSR_Risks_Opportunities.ID", "PSR_Risks_Opportunities.Net_Risk_OCB", "PSR_Risks_Opportunities.Net_Risk_RCB", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Constr_Inst", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Country", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Eng", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Ext_of_Time", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Hand_over_with_Proposa", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Prj_Mng", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_for_Proc", "PSR_Risks_Opportunities.Opp_Expected_Current_Forecast_Total", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Constr_Inst", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Country", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Eng", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Ext_of_Time", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Hand_Over_with_Proposal", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Prj_Mng", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_for_Proc", "PSR_Risks_Opportunities.Opp_Occur_As_Prj_Conting_Total", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Constr_Inst", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Country", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Eng", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Ext_of_Time", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Hand_over_with_Propos", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Prj_Mng", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_for_Proc", "PSR_Risks_Opportunities.Opp_Occur_Effect_Margin_Impact_Total", "PSR_Risks_Opportunities.Range_Of_Gross_Margin_Forecast_Downside_worst_case", "PSR_Risks_Opportunities.Range_Of_Gross_Margin_Forecast_Upside_best_case", "PSR_Risks_Opportunities.Risk_Coverage", "PSR_Risks_Opportunities.Risk_Exposure", "PSR_Risks_Opportunities.Risk_Ratio", "PSR_Risks_Opportunities.Risk_Register_Reference_Portal_ID", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_Eng", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Country", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Hand_over_with_Propo", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Liquidated_Damages", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_for_Proc", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_Running_Costs_for_Delay", "PSR_Risks_Opportunities.Risks_Expected_Current_Forecast_Total", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Country", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Eng", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Hand_Over_with_Pr", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Liquidated_Damage", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Proc", "PSR_Risks_Opportunities.Risks_Mng_Conting_Current_Forecast_for_Running_Costs_for", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_Eng", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Country", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Hand_over_with_Prop", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Liquidated_Damages", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_for_Proc", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_Running_Costs_for_Delay", "PSR_Risks_Opportunities.Risks_Occur_Effect_Margin_Impact_Total", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Country", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Eng", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Hand_Over_with_Proposal", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Liquidated_Damages", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Proc", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_for_Running_Costs_for_Delay", "PSR_Risks_Opportunities.Risks_Occur_Utilized_Conting_Total", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Constr_Inst", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Country", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Eng", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Hand_Over_with_Pr", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Liquidated_Damage", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Prj_Mng", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Proc", "PSR_Risks_Opportunities.Risks_Prj_Conting_Current_Forecast_for_Running_Costs_for", "PSR_Risks_Opportunities.Risks_Residual_Expected_Current_Forecast_Total", "PSR_Risks_Opportunities.Total_Opportunities_OCB", "PSR_Risks_Opportunities.Total_Opportunities_RCB", "PSR_Risks_Opportunities.Total_Revenues_Included_In_Forecast", "PSR_Risks_Opportunities.Total_Risk_OCB", "PSR_Risks_Opportunities.Total_Risk_RCB", "PSR_Risks_Opportunities.VAR 75 Score", "PSR_Risks_Opportunities.VAR_50"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"PSR_Risks_Opportunities.VAR_75", Int64.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

