table PSR_Revenues_status
	lineageTag: 490b60b0-a669-443d-8e94-8d87e56c3592

	column 'PSR_Revenues_Status.EL Pending CF'
		dataType: int64
		formatString: 0
		lineageTag: bdb21e5f-4a01-4315-a2f0-e0f2e3970169
		summarizeBy: sum
		sourceColumn: PSR_Revenues_Status.EL Pending CF

		annotation SummarizationSetBy = Automatic

	column 'PSR_Revenues_Status.P_Key'
		dataType: string
		lineageTag: ca7d5655-2ff7-4ba9-aeed-11a1561f46d3
		summarizeBy: none
		sourceColumn: PSR_Revenues_Status.P_Key

		annotation SummarizationSetBy = Automatic

	column _ConsolidationCode = LEFT(PSR_Revenues_status[PSR_Revenues_Status.P_Key], 8)
		lineageTag: 9321a606-a6f8-481e-9dff-402567a468e0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Forecast_Period =
			
			
			LOOKUPVALUE(
			    'PSR Group By'[_ForecastYearAxis],
			    'PSR Group By'[List_Data_GroupBy.Cons_Project],
			    PSR_Revenues_status[_ConsolidationCode]
			)
		lineageTag: d193daf2-d320-43f1-8593-4095b827d680
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition PSR_Revenues_status = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/RISCOP%20BI%20%26%20REPORTING", "PSR Report", [TypedMeasureColumns=true, Implementation="2.0"]),
				    Model1 = Source{[Id="Model"]}[Data],
				    Model2 = Model1{[Id="Model"]}[Data],
				    #"Added Items" = Cube.Transform(Model2,
				        {
				            {Cube.AddAndExpandDimensionColumn, "[PSR_Revenues_Status]", {"[PSR_Revenues_Status].[Amendment_Variations_Pending_Expected].[Amendment_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Amendment_Variations_Pending_Included].[Amendment_Variations_Pending_Included]", "[PSR_Revenues_Status].[Amendment_Variations_Pending_Included_ENI].[Amendment_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Bonus_Approved].[Bonus_Approved]", "[PSR_Revenues_Status].[Bonus_Variations_Pending_Expected].[Bonus_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Bonus_Variations_Pending_Included].[Bonus_Variations_Pending_Included]", "[PSR_Revenues_Status].[Bonus_Variations_Pending_Included_ENI].[Bonus_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Bonus_Variations_TBI_Expected].[Bonus_Variations_TBI_Expected]", "[PSR_Revenues_Status].[Bonus_Variations_TBI_Included].[Bonus_Variations_TBI_Included]", "[PSR_Revenues_Status].[Bonus_Variations_TBI_Included_ENI].[Bonus_Variations_TBI_Included_ENI]", "[PSR_Revenues_Status].[Change_Orders_Approved].[Change_Orders_Approved]", "[PSR_Revenues_Status].[Change_Orders_Variations_Approved].[Change_Orders_Variations_Approved]", "[PSR_Revenues_Status].[Change_Orders_Variations_Pending_Expected].[Change_Orders_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Change_Orders_Variations_Pending_Included].[Change_Orders_Variations_Pending_Included]", "[PSR_Revenues_Status].[Change_Orders_Variations_Pending_Included_ENI].[Change_Orders_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Change_Orders_Variations_Received_Expected].[Change_Orders_Variations_Received_Expected]", "[PSR_Revenues_Status].[Change_Orders_Variations_Received_Included].[Change_Orders_Variations_Received_Included]", "[PSR_Revenues_Status].[Change_Orders_Variations_TBI_Expected].[Change_Orders_Variations_TBI_Expected]", "[PSR_Revenues_Status].[Change_Orders_Variations_TBI_Included].[Change_Orders_Variations_TBI_Included]", "[PSR_Revenues_Status].[Change_Orders_Variations_TBI_Included_ENI].[Change_Orders_Variations_TBI_Included_ENI]", "[PSR_Revenues_Status].[Change_Orders_Variations_TBR_Expected].[Change_Orders_Variations_TBR_Expected]", "[PSR_Revenues_Status].[Change_Orders_Variations_TBR_Included].[Change_Orders_Variations_TBR_Included]", "[PSR_Revenues_Status].[Claims_Approved].[Claims_Approved]", "[PSR_Revenues_Status].[Claims_Variations_Approved].[Claims_Variations_Approved]", "[PSR_Revenues_Status].[Claims_Variations_Pending_Expected].[Claims_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Claims_Variations_Pending_Included].[Claims_Variations_Pending_Included]", "[PSR_Revenues_Status].[Claims_Variations_Pending_Included_ENI].[Claims_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Claims_Variations_Received_Expected].[Claims_Variations_Received_Expected]", "[PSR_Revenues_Status].[Claims_Variations_Received_Included].[Claims_Variations_Received_Included]", "[PSR_Revenues_Status].[Claims_Variations_TBI_Expected].[Claims_Variations_TBI_Expected]", "[PSR_Revenues_Status].[Claims_Variations_TBI_Included].[Claims_Variations_TBI_Included]", "[PSR_Revenues_Status].[Claims_Variations_TBI_Included_ENI].[Claims_Variations_TBI_Included_ENI]", "[PSR_Revenues_Status].[Claims_Variations_TBR_Expected].[Claims_Variations_TBR_Expected]", "[PSR_Revenues_Status].[Claims_Variations_TBR_Included].[Claims_Variations_TBR_Included]", "[PSR_Revenues_Status].[Descoping_Approved].[Descoping_Approved]", "[PSR_Revenues_Status].[Descoping_Variations_Approved].[Descoping_Variations_Approved]", "[PSR_Revenues_Status].[Descoping_Variations_Pending_Expected].[Descoping_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Descoping_Variations_Pending_Included].[Descoping_Variations_Pending_Included]", "[PSR_Revenues_Status].[Descoping_Variations_Pending_Included_ENI].[Descoping_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Descoping_Variations_Received_Expected].[Descoping_Variations_Received_Expected]", "[PSR_Revenues_Status].[Descoping_Variations_Received_Included].[Descoping_Variations_Received_Included]", "[PSR_Revenues_Status].[Descoping_Variations_TBI_Expected].[Descoping_Variations_TBI_Expected]", "[PSR_Revenues_Status].[Descoping_Variations_TBI_Included].[Descoping_Variations_TBI_Included]", "[PSR_Revenues_Status].[Descoping_Variations_TBI_Included_ENI].[Descoping_Variations_TBI_Included_ENI]", "[PSR_Revenues_Status].[Descoping_Variations_TBR_Expected].[Descoping_Variations_TBR_Expected]", "[PSR_Revenues_Status].[Descoping_Variations_TBR_Included].[Descoping_Variations_TBR_Included]", "[PSR_Revenues_Status].[EL Pending CF].[EL Pending CF]", "[PSR_Revenues_Status].[EL Pending ENI CF].[EL Pending ENI CF]", "[PSR_Revenues_Status].[Error_Upload].[Error_Upload]", "[PSR_Revenues_Status].[ID].[ID]", "[PSR_Revenues_Status].[Insurance_Coverage__Variations_Pending_Expected].[Insurance_Coverage__Variations_Pending_Expected]", "[PSR_Revenues_Status].[Insurance_Coverage__Variations_Pending_Included].[Insurance_Coverage__Variations_Pending_Included]", "[PSR_Revenues_Status].[Insurance_Coverage__Variations_Pending_Included_ENI].[Insurance_Coverage__Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Liquidated_Damages_Variations_Pending_Expected].[Liquidated_Damages_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Liquidated_Damages_Variations_Pending_Included].[Liquidated_Damages_Variations_Pending_Included]", "[PSR_Revenues_Status].[Liquidated_Damages_Variations_Pending_Included_ENI].[Liquidated_Damages_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Management_Contingencies_Associated_to_Risk_CF].[Management_Contingencies_Associated_to_Risk_CF]", "[PSR_Revenues_Status].[Management_Contingencies_Associated_to_Risk_RCB].[Management_Contingencies_Associated_to_Risk_RCB]", "[PSR_Revenues_Status].[Management_Contingencies_Not_Associated_to_Risk_CF].[Management_Contingencies_Not_Associated_to_Risk_CF]", "[PSR_Revenues_Status].[Management_Contingencies_Rel_for_Margin_Incr_Util_Conting].[Management_Contingencies_Rel_for_Margin_Incr_Util_Conting]", "[PSR_Revenues_Status].[Of_which_Management_Contingencies_Util_Conting].[Of_which_Management_Contingencies_Util_Conting]", "[PSR_Revenues_Status].[Options_Approved].[Options_Approved]", "[PSR_Revenues_Status].[Options_Variations_Pending_Expected].[Options_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Options_Variations_Pending_Included].[Options_Variations_Pending_Included]", "[PSR_Revenues_Status].[Options_Variations_Pending_Included_ENI].[Options_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Options_Variations_TBI_Expected].[Options_Variations_TBI_Expected]", "[PSR_Revenues_Status].[Options_Variations_TBI_Included].[Options_Variations_TBI_Included]", "[PSR_Revenues_Status].[Options_Variations_TBI_Included_ENI].[Options_Variations_TBI_Included_ENI]", "[PSR_Revenues_Status].[Original_Base_Contract_Approved].[Original_Base_Contract_Approved]", "[PSR_Revenues_Status].[Original_Base_Contract_Variations_Pending_Expected].[Original_Base_Contract_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Original_Base_Contract_Variations_Pending_Included].[Original_Base_Contract_Variations_Pending_Included]", "[PSR_Revenues_Status].[Original_Base_Contract_Variations_Pending_Included_ENI].[Original_Base_Contract_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Other_Revenues_Variations_Pending_Expected].[Other_Revenues_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Other_Revenues_Variations_Pending_Included].[Other_Revenues_Variations_Pending_Included]", "[PSR_Revenues_Status].[Other_Revenues_Variations_Pending_Included_ENI].[Other_Revenues_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[P_Key].[P_Key]", "[PSR_Revenues_Status].[Penalties_Approved].[Penalties_Approved]", "[PSR_Revenues_Status].[Penalties_Variations_Approved].[Penalties_Variations_Approved]", "[PSR_Revenues_Status].[Penalties_Variations_Pending_Expected].[Penalties_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Penalties_Variations_Pending_Included].[Penalties_Variations_Pending_Included]", "[PSR_Revenues_Status].[Penalties_Variations_Pending_Included_ENI].[Penalties_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Penalties_Variations_Received_Expected].[Penalties_Variations_Received_Expected]", "[PSR_Revenues_Status].[Penalties_Variations_Received_Included].[Penalties_Variations_Received_Included]", "[PSR_Revenues_Status].[Penalties_Variations_TBI_Expected].[Penalties_Variations_TBI_Expected]", "[PSR_Revenues_Status].[Penalties_Variations_TBI_Included].[Penalties_Variations_TBI_Included]", "[PSR_Revenues_Status].[Penalties_Variations_TBI_Included_ENI].[Penalties_Variations_TBI_Included_ENI]", "[PSR_Revenues_Status].[Penalties_Variations_TBR_Expected].[Penalties_Variations_TBR_Expected]", "[PSR_Revenues_Status].[Penalties_Variations_TBR_Included].[Penalties_Variations_TBR_Included]", "[PSR_Revenues_Status].[Provisional_Other_variation_Approved].[Provisional_Other_variation_Approved]", "[PSR_Revenues_Status].[Provisional_Other_variation_Variations_Pending_Expected].[Provisional_Other_variation_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Provisional_Other_variation_Variations_Pending_Included].[Provisional_Other_variation_Variations_Pending_Included]", "[PSR_Revenues_Status].[Provisional_Other_variation_Variations_Pending_Included_ENI].[Provisional_Other_variation_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Provisional_Other_variation_Variations_TBI_Expected].[Provisional_Other_variation_Variations_TBI_Expected]", "[PSR_Revenues_Status].[Provisional_Other_variation_Variations_TBI_Included].[Provisional_Other_variation_Variations_TBI_Included]", "[PSR_Revenues_Status].[Provisional_Other_variation_Variations_TBI_Included_ENI].[Provisional_Other_variation_Variations_TBI_Included_ENI]", "[PSR_Revenues_Status].[Reimbursable_Approved].[Reimbursable_Approved]", "[PSR_Revenues_Status].[Reimbursable_Variations_Pending_Expected].[Reimbursable_Variations_Pending_Expected]", "[PSR_Revenues_Status].[Reimbursable_Variations_Pending_Included].[Reimbursable_Variations_Pending_Included]", "[PSR_Revenues_Status].[Reimbursable_Variations_Pending_Included_ENI].[Reimbursable_Variations_Pending_Included_ENI]", "[PSR_Revenues_Status].[Reimbursable_Variations_TBI_Expected].[Reimbursable_Variations_TBI_Expected]", "[PSR_Revenues_Status].[Reimbursable_Variations_TBI_Included].[Reimbursable_Variations_TBI_Included]", "[PSR_Revenues_Status].[Reimbursable_Variations_TBI_Included_ENI].[Reimbursable_Variations_TBI_Included_ENI]", "[PSR_Revenues_Status].[Total_Variations_Pending_Requested_ENI].[Total_Variations_Pending_Requested_ENI]"}, {"PSR_Revenues_Status.Amendment_Variations_Pending_Expected", "PSR_Revenues_Status.Amendment_Variations_Pending_Included", "PSR_Revenues_Status.Amendment_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Bonus_Approved", "PSR_Revenues_Status.Bonus_Variations_Pending_Expected", "PSR_Revenues_Status.Bonus_Variations_Pending_Included", "PSR_Revenues_Status.Bonus_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Bonus_Variations_TBI_Expected", "PSR_Revenues_Status.Bonus_Variations_TBI_Included", "PSR_Revenues_Status.Bonus_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Change_Orders_Approved", "PSR_Revenues_Status.Change_Orders_Variations_Approved", "PSR_Revenues_Status.Change_Orders_Variations_Pending_Expected", "PSR_Revenues_Status.Change_Orders_Variations_Pending_Included", "PSR_Revenues_Status.Change_Orders_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Change_Orders_Variations_Received_Expected", "PSR_Revenues_Status.Change_Orders_Variations_Received_Included", "PSR_Revenues_Status.Change_Orders_Variations_TBI_Expected", "PSR_Revenues_Status.Change_Orders_Variations_TBI_Included", "PSR_Revenues_Status.Change_Orders_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Change_Orders_Variations_TBR_Expected", "PSR_Revenues_Status.Change_Orders_Variations_TBR_Included", "PSR_Revenues_Status.Claims_Approved", "PSR_Revenues_Status.Claims_Variations_Approved", "PSR_Revenues_Status.Claims_Variations_Pending_Expected", "PSR_Revenues_Status.Claims_Variations_Pending_Included", "PSR_Revenues_Status.Claims_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Claims_Variations_Received_Expected", "PSR_Revenues_Status.Claims_Variations_Received_Included", "PSR_Revenues_Status.Claims_Variations_TBI_Expected", "PSR_Revenues_Status.Claims_Variations_TBI_Included", "PSR_Revenues_Status.Claims_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Claims_Variations_TBR_Expected", "PSR_Revenues_Status.Claims_Variations_TBR_Included", "PSR_Revenues_Status.Descoping_Approved", "PSR_Revenues_Status.Descoping_Variations_Approved", "PSR_Revenues_Status.Descoping_Variations_Pending_Expected", "PSR_Revenues_Status.Descoping_Variations_Pending_Included", "PSR_Revenues_Status.Descoping_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Descoping_Variations_Received_Expected", "PSR_Revenues_Status.Descoping_Variations_Received_Included", "PSR_Revenues_Status.Descoping_Variations_TBI_Expected", "PSR_Revenues_Status.Descoping_Variations_TBI_Included", "PSR_Revenues_Status.Descoping_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Descoping_Variations_TBR_Expected", "PSR_Revenues_Status.Descoping_Variations_TBR_Included", "PSR_Revenues_Status.EL Pending CF", "PSR_Revenues_Status.EL Pending ENI CF", "PSR_Revenues_Status.Error_Upload", "PSR_Revenues_Status.ID", "PSR_Revenues_Status.Insurance_Coverage__Variations_Pending_Expected", "PSR_Revenues_Status.Insurance_Coverage__Variations_Pending_Included", "PSR_Revenues_Status.Insurance_Coverage__Variations_Pending_Included_ENI", "PSR_Revenues_Status.Liquidated_Damages_Variations_Pending_Expected", "PSR_Revenues_Status.Liquidated_Damages_Variations_Pending_Included", "PSR_Revenues_Status.Liquidated_Damages_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Management_Contingencies_Associated_to_Risk_CF", "PSR_Revenues_Status.Management_Contingencies_Associated_to_Risk_RCB", "PSR_Revenues_Status.Management_Contingencies_Not_Associated_to_Risk_CF", "PSR_Revenues_Status.Management_Contingencies_Rel_for_Margin_Incr_Util_Conting", "PSR_Revenues_Status.Of_which_Management_Contingencies_Util_Conting", "PSR_Revenues_Status.Options_Approved", "PSR_Revenues_Status.Options_Variations_Pending_Expected", "PSR_Revenues_Status.Options_Variations_Pending_Included", "PSR_Revenues_Status.Options_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Options_Variations_TBI_Expected", "PSR_Revenues_Status.Options_Variations_TBI_Included", "PSR_Revenues_Status.Options_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Original_Base_Contract_Approved", "PSR_Revenues_Status.Original_Base_Contract_Variations_Pending_Expected", "PSR_Revenues_Status.Original_Base_Contract_Variations_Pending_Included", "PSR_Revenues_Status.Original_Base_Contract_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Other_Revenues_Variations_Pending_Expected", "PSR_Revenues_Status.Other_Revenues_Variations_Pending_Included", "PSR_Revenues_Status.Other_Revenues_Variations_Pending_Included_ENI", "PSR_Revenues_Status.P_Key", "PSR_Revenues_Status.Penalties_Approved", "PSR_Revenues_Status.Penalties_Variations_Approved", "PSR_Revenues_Status.Penalties_Variations_Pending_Expected", "PSR_Revenues_Status.Penalties_Variations_Pending_Included", "PSR_Revenues_Status.Penalties_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Penalties_Variations_Received_Expected", "PSR_Revenues_Status.Penalties_Variations_Received_Included", "PSR_Revenues_Status.Penalties_Variations_TBI_Expected", "PSR_Revenues_Status.Penalties_Variations_TBI_Included", "PSR_Revenues_Status.Penalties_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Penalties_Variations_TBR_Expected", "PSR_Revenues_Status.Penalties_Variations_TBR_Included", "PSR_Revenues_Status.Provisional_Other_variation_Approved", "PSR_Revenues_Status.Provisional_Other_variation_Variations_Pending_Expected", "PSR_Revenues_Status.Provisional_Other_variation_Variations_Pending_Included", "PSR_Revenues_Status.Provisional_Other_variation_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Provisional_Other_variation_Variations_TBI_Expected", "PSR_Revenues_Status.Provisional_Other_variation_Variations_TBI_Included", "PSR_Revenues_Status.Provisional_Other_variation_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Reimbursable_Approved", "PSR_Revenues_Status.Reimbursable_Variations_Pending_Expected", "PSR_Revenues_Status.Reimbursable_Variations_Pending_Included", "PSR_Revenues_Status.Reimbursable_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Reimbursable_Variations_TBI_Expected", "PSR_Revenues_Status.Reimbursable_Variations_TBI_Included", "PSR_Revenues_Status.Reimbursable_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Total_Variations_Pending_Requested_ENI"}},
				            {Cube.AddMeasureColumn, "Contract Value", "[Measures].[Contract Value]"},
				            {Cube.AddMeasureColumn, "EL Pending Deviation", "[Measures].[EL Pending Deviation]"},
				            {Cube.AddMeasureColumn, "EL Pending ENI Deviation", "[Measures].[EL Pending ENI Deviation]"}
				        }),
				
				    // Filtro per rimuovere dati prima del 2022 (non essendoci una colonna "anno", il filtro è applicato cercando delle stringhe nella chiave)
				    #"Filtered Rows_year" = Table.SelectRows(#"Added Items", each not Text.Contains([PSR_Revenues_Status.P_Key], "_2010_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2011_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2012_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2013_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2014_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2015_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2016_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2017_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2018_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2019_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2020_") and not Text.Contains([PSR_Revenues_Status.P_Key], "_2021_")),
				
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows_year",{"Contract Value", "EL Pending Deviation", "EL Pending ENI Deviation", "PSR_Revenues_Status.Amendment_Variations_Pending_Expected", "PSR_Revenues_Status.Amendment_Variations_Pending_Included", "PSR_Revenues_Status.Amendment_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Bonus_Approved", "PSR_Revenues_Status.Bonus_Variations_Pending_Expected", "PSR_Revenues_Status.Bonus_Variations_Pending_Included", "PSR_Revenues_Status.Bonus_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Bonus_Variations_TBI_Expected", "PSR_Revenues_Status.Bonus_Variations_TBI_Included", "PSR_Revenues_Status.Bonus_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Change_Orders_Approved", "PSR_Revenues_Status.Change_Orders_Variations_Approved", "PSR_Revenues_Status.Change_Orders_Variations_Pending_Expected", "PSR_Revenues_Status.Change_Orders_Variations_Pending_Included", "PSR_Revenues_Status.Change_Orders_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Change_Orders_Variations_Received_Expected", "PSR_Revenues_Status.Change_Orders_Variations_Received_Included", "PSR_Revenues_Status.Change_Orders_Variations_TBI_Expected", "PSR_Revenues_Status.Change_Orders_Variations_TBI_Included", "PSR_Revenues_Status.Change_Orders_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Change_Orders_Variations_TBR_Expected", "PSR_Revenues_Status.Change_Orders_Variations_TBR_Included", "PSR_Revenues_Status.Claims_Approved", "PSR_Revenues_Status.Claims_Variations_Approved", "PSR_Revenues_Status.Claims_Variations_Pending_Expected", "PSR_Revenues_Status.Claims_Variations_Pending_Included", "PSR_Revenues_Status.Claims_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Claims_Variations_Received_Expected", "PSR_Revenues_Status.Claims_Variations_Received_Included", "PSR_Revenues_Status.Claims_Variations_TBI_Expected", "PSR_Revenues_Status.Claims_Variations_TBI_Included", "PSR_Revenues_Status.Claims_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Claims_Variations_TBR_Expected", "PSR_Revenues_Status.Claims_Variations_TBR_Included", "PSR_Revenues_Status.Descoping_Approved", "PSR_Revenues_Status.Descoping_Variations_Approved", "PSR_Revenues_Status.Descoping_Variations_Pending_Expected", "PSR_Revenues_Status.Descoping_Variations_Pending_Included", "PSR_Revenues_Status.Descoping_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Descoping_Variations_Received_Expected", "PSR_Revenues_Status.Descoping_Variations_Received_Included", "PSR_Revenues_Status.Descoping_Variations_TBI_Expected", "PSR_Revenues_Status.Descoping_Variations_TBI_Included", "PSR_Revenues_Status.Descoping_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Descoping_Variations_TBR_Expected", "PSR_Revenues_Status.Descoping_Variations_TBR_Included", "PSR_Revenues_Status.EL Pending ENI CF", "PSR_Revenues_Status.Error_Upload", "PSR_Revenues_Status.ID", "PSR_Revenues_Status.Insurance_Coverage__Variations_Pending_Expected", "PSR_Revenues_Status.Insurance_Coverage__Variations_Pending_Included", "PSR_Revenues_Status.Insurance_Coverage__Variations_Pending_Included_ENI", "PSR_Revenues_Status.Liquidated_Damages_Variations_Pending_Expected", "PSR_Revenues_Status.Liquidated_Damages_Variations_Pending_Included", "PSR_Revenues_Status.Liquidated_Damages_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Management_Contingencies_Associated_to_Risk_CF", "PSR_Revenues_Status.Management_Contingencies_Associated_to_Risk_RCB", "PSR_Revenues_Status.Management_Contingencies_Not_Associated_to_Risk_CF", "PSR_Revenues_Status.Management_Contingencies_Rel_for_Margin_Incr_Util_Conting", "PSR_Revenues_Status.Of_which_Management_Contingencies_Util_Conting", "PSR_Revenues_Status.Options_Approved", "PSR_Revenues_Status.Options_Variations_Pending_Expected", "PSR_Revenues_Status.Options_Variations_Pending_Included", "PSR_Revenues_Status.Options_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Options_Variations_TBI_Expected", "PSR_Revenues_Status.Options_Variations_TBI_Included", "PSR_Revenues_Status.Options_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Original_Base_Contract_Approved", "PSR_Revenues_Status.Original_Base_Contract_Variations_Pending_Expected", "PSR_Revenues_Status.Original_Base_Contract_Variations_Pending_Included", "PSR_Revenues_Status.Original_Base_Contract_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Other_Revenues_Variations_Pending_Expected", "PSR_Revenues_Status.Other_Revenues_Variations_Pending_Included", "PSR_Revenues_Status.Other_Revenues_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Penalties_Approved", "PSR_Revenues_Status.Penalties_Variations_Approved", "PSR_Revenues_Status.Penalties_Variations_Pending_Expected", "PSR_Revenues_Status.Penalties_Variations_Pending_Included", "PSR_Revenues_Status.Penalties_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Penalties_Variations_Received_Expected", "PSR_Revenues_Status.Penalties_Variations_Received_Included", "PSR_Revenues_Status.Penalties_Variations_TBI_Expected", "PSR_Revenues_Status.Penalties_Variations_TBI_Included", "PSR_Revenues_Status.Penalties_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Penalties_Variations_TBR_Expected", "PSR_Revenues_Status.Penalties_Variations_TBR_Included", "PSR_Revenues_Status.Provisional_Other_variation_Approved", "PSR_Revenues_Status.Provisional_Other_variation_Variations_Pending_Expected", "PSR_Revenues_Status.Provisional_Other_variation_Variations_Pending_Included", "PSR_Revenues_Status.Provisional_Other_variation_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Provisional_Other_variation_Variations_TBI_Expected", "PSR_Revenues_Status.Provisional_Other_variation_Variations_TBI_Included", "PSR_Revenues_Status.Provisional_Other_variation_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Reimbursable_Approved", "PSR_Revenues_Status.Reimbursable_Variations_Pending_Expected", "PSR_Revenues_Status.Reimbursable_Variations_Pending_Included", "PSR_Revenues_Status.Reimbursable_Variations_Pending_Included_ENI", "PSR_Revenues_Status.Reimbursable_Variations_TBI_Expected", "PSR_Revenues_Status.Reimbursable_Variations_TBI_Included", "PSR_Revenues_Status.Reimbursable_Variations_TBI_Included_ENI", "PSR_Revenues_Status.Total_Variations_Pending_Requested_ENI"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"PSR_Revenues_Status.EL Pending CF", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

